# Generated by Django 4.2.3 on 2024-04-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='class_name',
        ),
    ]
