# Generated by Django 4.2.3 on 2024-04-03 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_register_class_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='Registers',
        ),
    ]
